
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        DB_class
* GENERATION DATE:  07.03.2015
* CLASS FILE:       C:\wamp\www\sql-essentials\gen/generated_classes/class.DB_class.php
* FOR MYSQL TABLE:  news
* FOR MYSQL DB:     campus_news
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class DB_class
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $title;   // (normal Attribute)
var $details;   // (normal Attribute)
var $upload_date;   // (normal Attribute)
var $type;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function DB_class()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function gettitle()
{
return $this->title;
}

function getdetails()
{
return $this->details;
}

function getupload_date()
{
return $this->upload_date;
}

function gettype()
{
return $this->type;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function settitle($val)
{
$this->title =  $val;
}

function setdetails($val)
{
$this->details =  $val;
}

function setupload_date($val)
{
$this->upload_date =  $val;
}

function settype($val)
{
$this->type =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM news WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id = $row->id;

$this->title = $row->title;

$this->details = $row->details;

$this->upload_date = $row->upload_date;

$this->type = $row->type;

}

public function select_all_Query($offset)
{
	$myquery = "SELECT * FROM news ";
	$myquery .= "WHERE type = '$this->gettype()' ";
	$myquery .= "LIMIT 2 ";
	$myquery .= "OFFSET {$offset} ";
	$sql = $myquery;

	$result =  $this->database->query($sql);
	$result = $this->database->result;
	$_show = array();
	while($row = mysql_fetch_assoc($result))
	{
		$show[] = $row;
	}

	return $show;
}

public function mySelectQuery($column, $table, $filter_attr, $val)
{
	$myquery = "SELECT {$column} ";
	$myquery .= "FROM {$table} ";
	$myquery .= "WHERE {$filter_attr} > '{$val}' ";
	$sql = $myquery;
}
	

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM news WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO news ( title,details,upload_date,type ) VALUES ( '$this->title','$this->details','$this->upload_date','$this->type' )";
$result = $this->database->query($sql);
$this->id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE news SET  title = '$this->title',details = '$this->details',upload_date = '$this->upload_date',type = '$this->type' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
